services:
  - type: web
    name: orbis-finance
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /login
    envVars:
      - key: PORT
        value: 10000
      - key: APP_SECRET_KEY
        generateValue: true
      - key: BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
